currentVariable testing

diff --git a/Bash/hyprlandConfigUpdate b/Bash/hyprlandConfigUpdate
--- a/Bash/hyprlandConfigUpdate
+++ b/Bash/hyprlandConfigUpdate
@@ -1,5 +1,17 @@
 #!/bin/bash
 
+VARS_FILE="/home/$USER/.config/hypr/currentVariables"
+BACKUP_VARS_FILE="/home/$USER/Hyprland2.0/HyprV/current/currentVariables"
+
+# Check if vars.sh exists
+if [[ ! -f "$VARS_FILE" ]]; then
+    echo "vars.sh not found. Copying from backup..."
+    cp "$BACKUP_VARS_FILE" "$VARS_FILE" || {
+        echo "Failed to copy vars.sh. Exiting."
+        exit 1
+    }
+fi
+
 source /home/$USER/.config/hypr/currentVariables
 
 sudo su <<HERE
@@ -12,118 +24,56 @@ git clone https://github.com/GuillaumeGodin/Hyprland2.0
 
 sleep 1
 
-if test -e "/home/$USER/.config/hypr/currentVariables"; then
+rm -r /home/$USER/.config/HyprV
+cp -r /home/$USER/Hyprland2.0/HyprV /home/$USER/.config/HyprV
 
-    rm -r /home/$USER/.config/HyprV
-    cp -r /home/$USER/Hyprland2.0/HyprV /home/$USER/.config/HyprV
+# gtk (thunar)
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/gtk-3.0/gtk.css
+# wofi
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/wofi/style.css
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wofi/style/wofi_dark.css
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wofi/style/wofi_light.css
+# starship shell
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/starship/starship.toml
+# waybar
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/waybar/style/waybar_dark.css
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/waybar/style/waybar_light.css
+sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
+sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/waybar/conf/waybar_bottom.jsonc
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonApps.py
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonScripts.py
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonFiles.py
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonPower.py
+# wlogout
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wlogout/style/wlogout_dark.css
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wlogout/style/wlogout_light.css
+# mako
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/mako/conf/mako_dark
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/mako/conf/mako_light
+# firefox
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.mozilla/firefox/*.default-release/chrome/userChrome.css
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.mozilla/firefox/*.default-release/chrome/userContent.css
+# librewolf
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.librewolf/*.default-default/chrome/userChrome.css
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.librewolf/*.default-default/chrome/userContent.css
+# current
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/current/currentColor
+sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/current/currentMonitor
+sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/current/currentKeyboard
+# keyboard
+sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
+sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/hyprv_util
+#hyprland (border)
+sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/hypr/hyprland.conf
 
-    # gtk (thunar)
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/gtk-3.0/gtk.css
-    # wofi
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/wofi/style.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wofi/style/wofi_dark.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wofi/style/wofi_light.css
-    # starship shell
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/starship/starship.toml
-    # waybar
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/waybar/style/waybar_dark.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/waybar/style/waybar_light.css
-    sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
-    sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/waybar/conf/waybar_bottom.jsonc
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonApps.py
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonScripts.py
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonFiles.py
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonPower.py
-    # wlogout
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wlogout/style/wlogout_dark.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wlogout/style/wlogout_light.css
-    # mako
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/mako/conf/mako_dark
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/mako/conf/mako_light
-    # firefox
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.mozilla/firefox/*.default-release/chrome/userChrome.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.mozilla/firefox/*.default-release/chrome/userContent.css
-    # librewolf
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.librewolf/*.default-default/chrome/userChrome.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.librewolf/*.default-default/chrome/userContent.css
-    # current
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/current/currentColor
-    sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/current/currentMonitor
-    sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/current/currentKeyboard
-    # keyboard
-    sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
-    sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/hyprv_util
-    #hyprland (border)
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/hypr/hyprland.conf
+sleep 1
 
-    sleep 1
+ln -sf /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc /home/$USER/.config/waybar/config.jsonc
+ln -sf /home/$USER/.config/HyprV/waybar/style/waybar_dark.css /home/$USER/.config/waybar/style.css
+ln -sf /home/$USER/.config/HyprV/kitty/MochaDark.conf /home/$USER/.config/HyprV/kitty/mocha.conf
+ln -sf /home/$USER/.config/HyprV/hypr/hyprland.conf /home/$USER/.config/hypr/hyprland.conf
 
-    ln -sf /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc /home/$USER/.config/waybar/config.jsonc
-    ln -sf /home/$USER/.config/HyprV/waybar/style/waybar_dark.css /home/$USER/.config/waybar/style.css
-    ln -sf /home/$USER/.config/HyprV/kitty/MochaDark.conf /home/$USER/.config/HyprV/kitty/mocha.conf
-    ln -sf /home/$USER/.config/HyprV/hypr/hyprland.conf /home/$USER/.config/hypr/hyprland.conf
+sleep 1
 
-    sleep 1
-
-    makoctl reload
-    hyprctl reload
-
-else
-    
-    cp /home/$USER/Hyprland2.0/HyprV/current/currentVariables /home/$USER/.config/hypr/currentVariables
-
-    rm -r /home/$USER/.config/HyprV
-    cp -r /home/$USER/Hyprland2.0/HyprV /home/$USER/.config/HyprV
-
-    # gtk (thunar)
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/gtk-3.0/gtk.css
-    # wofi
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/wofi/style.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wofi/style/wofi_dark.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wofi/style/wofi_light.css
-    # starship shell
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/starship/starship.toml
-    # waybar
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/waybar/style/waybar_dark.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/waybar/style/waybar_light.css
-    sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
-    sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/waybar/conf/waybar_bottom.jsonc
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonApps.py
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonScripts.py
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonFiles.py
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/waybar/buttonPower.py
-    # wlogout
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wlogout/style/wlogout_dark.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/wlogout/style/wlogout_light.css
-    # mako
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/mako/conf/mako_dark
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/mako/conf/mako_light
-    # firefox
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.mozilla/firefox/*.default-release/chrome/userChrome.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.mozilla/firefox/*.default-release/chrome/userContent.css
-    # librewolf
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.librewolf/*.default-default/chrome/userChrome.css
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.librewolf/*.default-default/chrome/userContent.css
-    # current
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/current/currentColor
-    sed -i "s/$defaultMonitor/$currentMonitor/g" /home/$USER/.config/HyprV/current/currentMonitor
-    sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/current/currentKeyboard
-    # keyboard
-    sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc
-    sed -i "s/$defaultKeyboard/$currentKeyboard/g" /home/$USER/.config/HyprV/hyprv_util
-    #hyprland (border)
-    sed -i "s/$defaultColor/$currentColor/g" /home/$USER/.config/HyprV/hypr/hyprland.conf
-
-    sleep 1
-
-    ln -sf /home/$USER/.config/HyprV/waybar/conf/waybar_top.jsonc /home/$USER/.config/waybar/config.jsonc
-    ln -sf /home/$USER/.config/HyprV/waybar/style/waybar_dark.css /home/$USER/.config/waybar/style.css
-    ln -sf /home/$USER/.config/HyprV/kitty/MochaDark.conf /home/$USER/.config/HyprV/kitty/mocha.conf
-    ln -sf /home/$USER/.config/HyprV/hypr/hyprland.conf /home/$USER/.config/hypr/hyprland.conf
-
-    sleep 1
-
-    makoctl reload
-    hyprctl reload
-
-fi
+makoctl reload
+hyprctl reload
